language: java

sudo: false

# http://docs.travis-ci.com/user/caching/#Arbitrary-directories
cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk11
  - openjdk8

matrix:
  fast_finish: true

before_install:
  - pip install --user -r requirements.txt

script:
  - mvn install -DskipSphinxTests=true

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - target/bio-formats-documentation-*
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk11
